- debug:
    msg: "INSTALLING DOCKER RUNTIME"

- name: Adding docker gpg key
  apt_key:
    url: "{{ apt_gpg_key }}"
    state: present

- name: Adding docker repository
  apt_repository:
    repo: "{{ apt_repo_data }}"

- name: Installing docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Installing python-pip
  apt:
    name: python-pip
    state: present

- name: Installing python3-pip
  apt:
    name: python3-pip
    state: present

- name: Installing docker-py
  pip:
    name: docker-py
    state: present



